version: 2
updates:
  - package-ecosystem: "npm"
    directory: '/'
    schedule:
      interval: "daily"
      time: '00:00'
    reviewers:
      - imsk17
    assignees:
      - imsk17
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope