name: Generate typechain and contract

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: setup node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x
          cache: yarn
          cache-dependency-path: |
            yarn.lock
            yarn.contract.lock
      - name: dep
        run: yarn

      - name: build
        run: yarn build-typings

      - name: prepare package
        working-directory: ./package_out
        run: mkdir out && mv package.json out && mv dist out

      - name: Prepare Release
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: package_out/out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
